import type { ThemePreset } from './types';

export const presets: ThemePreset[] = [
  {
    id: 'spring',
    name: 'Spring Blossom',
    description: 'Soft pinks and fresh greens',
    parts: {
      colors: {
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: '#10b981',
        background: '#fdf2f8',
        surface: '#fce7f3',
        text: '#831843',
        textMuted: '#9d6b8a',
        border: '#fbcfe8',
      },
      typography: {},
      spacing: {},
      wallpaper: { src: '', blend: 'none', opacity: 0 },
      effects: { shadowStrength: 'subtle', glass: false, noise: false },
    },
  },
  {
    id: 'summer',
    name: 'Summer Vibes',
    description: 'Bright yellows and ocean blues',
    parts: {
      colors: {
        primary: '#f59e0b',
        secondary: '#06b6d4',
        accent: '#ef4444',
        background: '#fffbeb',
        surface: '#fef3c7',
        text: '#78350f',
        textMuted: '#a8a29e',
        border: '#fde68a',
      },
      typography: {},
      spacing: {},
      wallpaper: { src: '', blend: 'none', opacity: 0 },
      effects: { shadowStrength: 'medium', glass: false, noise: false },
    },
  },
  {
    id: 'autumn',
    name: 'Autumn Harvest',
    description: 'Warm earth tones and crisp air',
    parts: {
      colors: {
        primary: '#d97706',
        secondary: '#b45309',
        accent: '#b91c1c',
        background: '#fffbeb',
        surface: '#fef7ed',
        text: '#451a03',
        textMuted: '#92400e88',
        border: '#fde68a',
      },
      typography: {},
      spacing: {},
      wallpaper: { src: '', blend: 'none', opacity: 0 },
      effects: { shadowStrength: 'subtle', glass: false, noise: false },
    },
  },
  {
    id: 'winter',
    name: 'Winter Frost',
    description: 'Cool blues with frosted glass effects',
    parts: {
      colors: {
        primary: '#6366f1',
        secondary: '#3b82f6',
        accent: '#06b6d4',
        background: '#f0f9ff',
        surface: '#e0f2fe',
        text: '#0c4a6e',
        textMuted: '#94a3b8',
        border: '#bae6fd',
      },
      typography: {},
      spacing: {},
      wallpaper: { src: '', blend: 'none', opacity: 0 },
      effects: { shadowStrength: 'subtle', glass: true, noise: false },
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Dark mode with subtle glow',
    parts: {
      colors: {
        primary: '#818cf8',
        secondary: '#a78bfa',
        accent: '#fbbf24',
        background: '#0f172a',
        surface: '#1e293b',
        text: '#f1f5f9',
        textMuted: '#64748b',
        border: '#334155',
      },
      typography: {},
      spacing: {},
      wallpaper: { src: '', blend: 'none', opacity: 0 },
      effects: { shadowStrength: 'medium', glass: false, noise: true },
    },
  },
];
